# Generated by Django 3.1.12 on 2024-12-31 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbdmsapp', '0008_auto_20241231_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodrequest',
            old_name='fullname',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='bloodrequest',
            old_name='mobno',
            new_name='mobile_number',
        ),
        migrations.RenameField(
            model_name='bloodrequest',
            old_name='requirer',
            new_name='requester',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='regdate_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='fullname',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='mobno',
            new_name='mobile_number',
        ),
        migrations.RenameField(
            model_name='donorreg',
            old_name='regdate_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='donorreg',
            old_name='mobilenumber',
            new_name='mobile_number',
        ),
        migrations.RenameField(
            model_name='donorreg',
            old_name='admin',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='donid',
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='donor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bbdmsapp.donorreg'),
        ),
        migrations.AlterField(
            model_name='bloodgroup',
            name='id',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='bloodgroup',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='message',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'Admin'), (2, 'Donor'), (3, 'Requester')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='donorreg',
            name='address',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='donorreg',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='donorreg',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='donorreg',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='donorreg',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
