# Generated by Django 3.1.12 on 2025-01-01 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbdmsapp', '0010_auto_20250101_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodrequest',
            old_name='regdate_at',
            new_name='created_at',
        ),
    ]
