# Generated by Django 3.1.12 on 2025-01-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbdmsapp', '0011_auto_20250101_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodgroup',
            name='bloodgroup',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
